/*************************************************************************************************************
 *
 * Module: Ultrasonic Sensor
 *
 * File Name: ultrasonic_sensor.c
 *
 * Author: Asser Hosaam
 *
 ************************************************************************************************************/

#include "ultrasonic_sensor.h"
#include "gpio.h"
#include "icu.h"
#include "common_macros.h"
#include <util/delay.h>

/*----------------------------------------------global variables--------------------------------------------*/
static uint16 g_distance;
static uint16 g_time;
static uint8 g_edges_counter;

/*--------------------------------------------function definitions-------------------------------------------*/

/*************************************************************************************
**Description:
**Initialize the ICU driver as required.
**Set up the ICU callback function.
**Set the direction for the trigger pin as output through the GPIO driver.
**Inputs: None.
**Return: None
***************************************************************************************/
void Ultrasonic_init(void)
{
    ICU_setCallBack(Ultrasonic_edgeProcessing);
    GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORTID, ULTRASONIC_TRIGGER_PINID, PIN_OUTPUT);
}


/**************************************************************************************
**Description:
**Send the trigger pulse to the ultrasonic sensor.
**Inputs: None.
**Return: None.
***************************************************************************************/
void Ultrasonic_Trigger(void)
{
    GPIO_writePin(ULTRASONIC_TRIGGER_PORTID, ULTRASONIC_TRIGGER_PINID, LOGIC_HIGH);
    _delay_us(10);  // Trigger pulse must be at least 10 microseconds
    GPIO_writePin(ULTRASONIC_TRIGGER_PORTID, ULTRASONIC_TRIGGER_PINID, LOGIC_LOW);
}


/************************************************************************************
**Description:
**Send the trigger pulse by using the Ultrasonic_Trigger function.
**Start the measurement process via the ICU driver.
**Inputs: None.
**Return: The measured distance in centimeters.
************************************************************************************/
uint16 Ultrasonic_readDistance(void){
	/* sending pulses by the trigger*/
	Ultrasonic_Trigger();
	if(g_edges_counter==2)
	{
		//raising & falling -> 1 cycle
		g_edges_counter=0; //reset the counter of the edges
		/* equation to convert from time to distance*/
		g_distance = (g_time/117.6);
	}
	return (g_distance+1);
}

/**********************************************************************************
**Description:
**This is the callback function called by the ICU driver.
**It calculates the high time (pulse time) generated by the ultrasonic sensor.
**Inputs: None.
**Return: None
***********************************************************************************/
void Ultrasonic_edgeProcessing(void)
{
    g_edges_counter++;
    if (g_edges_counter == 1)
    {
        ICU_clearTimerValue();
        ICU_setEdgeDetectionType(FALLING);
    }
    else if (g_edges_counter == 2)
    {
        g_time = ICU_getInputCaptureValue();
        ICU_clearTimerValue();
        ICU_setEdgeDetectionType(RAISING);
    }
}

