/*************************************************************************************************************
 *
 * Module: Ultrasonic Sensor
 *
 * File Name: ultrasonic_sensor.h
 *
 * Author: Asser Hosaam
 *
 ************************************************************************************************************/

#ifndef ULTRASONIC_SENSOR_H_
#define ULTRASONIC_SENSOR_H_

#include "std_types.h"

/*--------------------------------------------definitions---------------------------------------------------*/

#define ULTRASONIC_TRIGGER_PORTID   PORTD_ID
#define ULTRASONIC_TRIGGER_PINID    PIN7_ID

/*--------------------------------------------function prototypes--------------------------------------------*/

/*************************************************************************************
**Description:
**Initialize the ICU driver as required.
**Set up the ICU callback function.
**Set the direction for the trigger pin as output through the GPIO driver.
**Inputs: None.
**Return: None
***************************************************************************************/
void Ultrasonic_init(void);

/**************************************************************************************
**Description:
**Send the trigger pulse to the ultrasonic sensor.
**Inputs: None.
**Return: None.
***************************************************************************************/
void Ultrasonic_Trigger(void);

/************************************************************************************
**Description:
**Send the trigger pulse by using the Ultrasonic_Trigger function.
**Start the measurement process via the ICU driver.
**Inputs: None.
**Return: The measured distance in centimeters.
************************************************************************************/
uint16 Ultrasonic_readDistance(void);

/**********************************************************************************
**Description:
**This is the callback function called by the ICU driver.
**It calculates the high time (pulse time) generated by the ultrasonic sensor.
**Inputs: None.
**Return: None
***********************************************************************************/
void Ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_SENSOR_H_ */
